<?php
$review=!empty($_GET['review']);$p=$_SESSION['bulk_preview']??null;
page_head($review?t('Nachricht prüfen','Review message'):t('Nachricht schreiben','Write a message'),'',link_button(t('Nachrichten','Messages'),'messages',[],'secondary'));
if($review && $p): ?>
<section class="card"><span class="eyebrow"><?=count($p['accounts'])?> <?=e(t('Konten','accounts'))?> · <?=count($p['student_ids'])?> <?=e(t('Schüler','students'))?></span><h2><?=e($p['subject'])?></h2><p><?=e(implode(', ',$p['accounts']))?></p><div class="notice"><?=e($p['email']?t('Private Unterhaltung je Konto. E-Mail-Hinweis nur bei aktivierten Benachrichtigungen.','A private conversation per account. Email notification only if enabled.'):t('Private Unterhaltung je Konto, ohne E-Mail-Hinweis.','A private conversation per account, without an email notification.'))?></div>
<?php $grouped=[];foreach($p['student_ids'] as $sid){$ss=student((int)$sid);$grouped[$ss['account_id']][]=$ss;}foreach($grouped as $aid=>$items):?><details <?=count($grouped)===1?'open':''?>><summary><?=e($p['accounts'][$aid]??'')?></summary><h3><?=e(template_text($p['subject'],$items[0]))?></h3><?php $specific=preg_match('/\{\{(student_name|first_name|tariff|outstanding|paid_through)\}\}/',$p['body']);$body=$specific?implode("\n\n────────\n\n",array_map(fn($s)=>template_text($p['body'],$s),$items)):template_text($p['body'],$items[0]);?><div class="prewrap"><?=e($body)?></div></details><?php endforeach ?>
<?php start_form('bulk_send');submit_button(t('Jetzt senden','Send now'));?></form><?=link_button(t('Zurück zum Entwurf','Back to draft'),'compose',['draft'=>1],'secondary')?></section>
<?php else:
$f=filters_from($_GET);$all=filtered_students($f);$tpl=!empty($_GET['template'])?one('SELECT * FROM message_templates WHERE id=?',[(int)$_GET['template']]):null;
$draft=!empty($_GET['draft'])&&$p?$p:null;
?>
<section class="card filter-card"><h2><?=e(t('Empfänger finden','Find recipients'))?></h2><?php render_filters($f,'compose');?><div class="saved-filters"><?php foreach(rows('SELECT * FROM saved_filters ORDER BY name') as $filter):?><a class="chip" href="<?=e(url('compose',json_decode($filter['criteria_json'],true)))?>"><?=e($filter['name'])?></a><?php endforeach ?></div></section>
<section class="card"><div class="saved-filters"><span><?=e(t('Vorlage:','Template:'))?></span><?php foreach(rows('SELECT * FROM message_templates ORDER BY name') as $template):?><a class="chip" href="<?=e(url('compose',$f+['template'=>$template['id']]))?>"><?=e($template['name'])?></a><?php endforeach ?></div>
<?php start_form('bulk_preview');?><div class="section-heading"><h2><?=e(t('Schüler auswählen','Select students'))?></h2><label class="check"><input type="checkbox" data-select-all="student_ids[]"><span><?=e(t('Alle auswählen','Select all'))?></span></label></div><div class="recipient-list">
<?php foreach($all as $s):$a=$s['account_id']?one('SELECT state,verified_at FROM accounts WHERE id=?',[$s['account_id']]):null;$eligible=$a&&$a['state']==='active'&&$a['verified_at'];?><label class="recipient <?=$eligible?'':'disabled'?>"><input type="checkbox" name="student_ids[]" value="<?=$s['id']?>" <?=$eligible?'':'disabled'?> <?=in_array((int)$s['id'],$draft['student_ids']??[],true)?'checked':''?>><span><strong><?=e($s['first_name'].' '.$s['last_name'])?></strong><small><?=e($eligible?($s['account_name']??''):t('Kein aktives, bestätigtes Konto','No active, verified account'))?></small></span></label><?php endforeach;if(!$all)echo '<p>'.e(t('Keine Schüler in dieser Auswahl.','No students in this selection.')).'</p>';?></div>
<?php input('subject',t('Betreff','Subject'),$draft['subject']??$tpl['subject']??'','text',true);input('body',t('Nachricht','Message'),$draft['body']??$tpl['body']??'','textarea',true);check_field('send_email',t('Zusätzlich per E-Mail auf die neue Nachricht hinweisen','Also send an email notification'),$draft['email']??true);submit_button(t('Empfänger und Nachricht prüfen','Review recipients and message'));?></form></section>
<?php endif ?>
