<?php
$staff=is_staff($user);$id=(int)($_GET['id']??0);$new=!empty($_GET['new']);
$unread=array_flip(unread_thread_ids($user));
$threads=rows('SELECT t.*,a.name AS account_name,(SELECT body FROM messages m WHERE m.thread_id=t.id ORDER BY m.id DESC LIMIT 1) AS last_message FROM threads t JOIN accounts a ON a.id=t.account_id'.($staff?'':' WHERE t.account_id=?').' ORDER BY t.updated_at DESC,t.id DESC',$staff?[]:[$user['id']]);
page_head(t('Nachrichten','Messages'),t('Persönlich im Portal antworten.','Reply privately inside the portal.'),link_button($staff?t('+ Nachricht / Gruppe','+ Message / group'):t('+ Neue Nachricht','+ New message'),$staff?'compose':'messages',$staff?[]:['new'=>1]));
?>
<div class="messages-grid"><aside class="card thread-list"><h2><?=e(t('Unterhaltungen','Conversations'))?></h2><?php if(!$threads):?><p class="muted"><?=e(t('Noch keine Nachrichten.','No messages yet.'))?></p><?php endif ?>
<?php foreach($threads as $thread):$isNew=isset($unread[(int)$thread['id']]);?><a class="thread-item <?=$id===(int)$thread['id']?'selected':''?> <?=$isNew?'unread':''?>" href="<?=e(url('messages',['id'=>$thread['id']]))?>"><div><strong><?=e($staff?$thread['account_name']:setting('club_name','Badminton'))?><?php if($isNew):?> <span class="dot" aria-hidden="true"></span><span class="visually-hidden"><?=e(t('ungelesen','unread'))?></span><?php endif ?></strong><small><?=e(fmt_date($thread['updated_at']))?></small></div><h3><?=e($thread['subject'])?></h3><p><?=e(mb_substr($thread['last_message']??'',0,90))?></p></a><?php endforeach ?></aside>
<section class="card conversation">
<?php if($id):$thread=thread_record($id);mark_thread_read($id,(int)$user['id']);?><div class="section-heading"><div><h2><?=e($thread['subject'])?></h2><small><?=e($thread['account_name'])?></small></div><?=icon('lock')?></div><div class="message-history">
<?php foreach(rows('SELECT m.*,a.name AS sender_name,a.role AS sender_role FROM messages m LEFT JOIN accounts a ON a.id=m.sender_id WHERE m.thread_id=? ORDER BY m.id',[$id]) as $m):$mine=(int)$m['sender_id']===(int)$user['id'];?><article class="message-bubble <?=$mine?'mine':''?>"><div class="message-meta"><strong><?=e($m['sender_name']??t('Gelöschtes Konto','Deleted account'))?></strong><time><?=e(fmt_datetime($m['created_at']))?></time></div><div class="prewrap"><?=e($m['body'])?></div></article><?php endforeach ?></div>
<?php start_form('message_send',['thread_id'=>$id]);input('body',t('Deine Antwort','Your reply'),'','textarea',true);submit_button(t('Antwort senden','Send reply'));?></form>
<?php elseif($new && !$staff):?><h2><?=e(t('Nachricht an die Trainerin','Message your coach'))?></h2><?php start_form('message_send');input('subject',t('Betreff','Subject'),'','text',true);input('body',t('Nachricht','Message'),'','textarea',true);submit_button(t('Nachricht senden','Send message'));?></form>
<?php else:empty_state(t('Zeit für Austausch.','Let’s talk.'),t('Öffne eine Unterhaltung oder schreibe eine neue Nachricht.','Open a conversation or write a new message.'));endif ?></section></div>
