<?php page_head(t('Postausgang','Outbox'),t('„Gesendet“ bedeutet: vom SMTP-Server angenommen. Zustellung und Antworten werden nicht geprüft.','“Sent” means accepted by the SMTP server. Delivery and replies are not tracked.')); ?>
<div class="card"><div class="section-heading"><div><h2><?=e(t('E-Mail-Versand','Email sending'))?></h2><small><?=e(t('Letzter Versandlauf: ','Last mail run: ').(setting('mail_last_run','')?:t('noch keiner','none yet')))?></small></div><?php if($user['role']==='admin'){start_form('mail_run',[],'inline-form');submit_button(t('Warteschlange senden','Send queued mail'),'secondary');echo '</form>';}?></div></div>
<?php $p=max(1,(int)($_GET['p']??1));$jobs=rows('SELECT m.*,a.name AS account_name FROM mail_jobs m LEFT JOIN accounts a ON a.id=m.account_id ORDER BY m.id DESC LIMIT 50 OFFSET '.(($p-1)*50)); ?>
<div class="card"><?php if(!$jobs)echo '<p class="muted">'.e(t('Noch keine E-Mails.','No emails yet.')).'</p>';foreach($jobs as $j):?><details class="mail-item"><summary><span><strong><?=e($j['subject'])?></strong><small><?=e($j['recipient'])?> · <?=e(fmt_date($j['created_at']))?></small></span><?php badge(['queued'=>t('Wartend','Queued'),'sent'=>t('Gesendet','Sent'),'failed'=>t('Fehlgeschlagen','Failed'),'cancelled'=>t('Abgebrochen','Cancelled')][$j['status']],$j['status']==='failed'?'red':($j['status']==='sent'?'green':''));?></summary>
<?php if($j['category']!=='security'&&$j['payload']):?><div class="prewrap"><?=e(unseal($j['payload']))?></div><?php endif ?>
<?php if($j['error']):?><p class="due"><?=e($j['error'])?></p><?php endif ?>
<p class="muted"><?=e(t('Versuche: ','Attempts: '))?><?=$j['attempts']?><?php if($j['sent_at'])echo ' · '.e(t('Gesendet: ','Sent: ').$j['sent_at'].' UTC');?></p>
<?php if($j['status']==='failed'&&$j['category']!=='security'){start_form('mail_retry',['id'=>$j['id']]);submit_button(t('Erneut vormerken','Queue again'),'secondary');echo '</form>';}?></details><?php endforeach ?></div>
<nav class="pagination"><?php if($p>1)echo link_button(t('Zurück','Previous'),'outbox',['p'=>$p-1],'secondary');if(count($jobs)===50)echo link_button(t('Weitere','More'),'outbox',['p'=>$p+1],'secondary');?></nav>
